# 2023-10-14 13:20
name: test -ref- act-build - x64, x86
run-name: test -ref- Build 2.5.2 - x64, x86

env:
   client_payload_name: 'far2m'
   client_payload_tag: '2.5.2'
   client_payload_sha: 'cf96728'
   client_payload_repo: 'deep-soft/far2m'
   client_payload_date: '20231015'
   client_payload_url: 'deep-soft/far2m'
   client_payload_message: 'far2m portable'

on:
  workflow_dispatch:
    inputs:
      # if: ${{ inputs.PLUGINS_EXTRA }}
      PLUGINS_EXTRA: 
        description: PLUGINS_EXTRA
        type: boolean
        required: true
        default: false
      # if: ${{ inputs.release_all }}
      release_all:
        description: Release all
        type: boolean
        required: true
        default: false

jobs:
  build-chroot:
    name: build ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          arch: [x86_64, x86]
          os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: deep-soft/checkout@v3

      - name: patch build_far2m.sh for run-after-cmake-before-package.sh
        shell: bash
        run: |
          sed -ibak '/find \$REPO_DIR -type d -path \"\*\/AppDir\"/i \\nbash ${GITHUB_WORKSPACE}/run-after-cmake-before-package.sh' ${GITHUB_WORKSPACE}/build_far2m.sh;
          cat ${GITHUB_WORKSPACE}/build_far2m.sh;

      - name: patch build_far2m.sh for PLUGINS_EXTRA
        if: ${{ inputs.PLUGINS_EXTRA }}
        shell: bash
        run: |
          sed -ibak "s!( cd \$plug!( mv far2m-\$plug \$plug \&\& \\n       cd \$plug!" ${GITHUB_WORKSPACE}/build_far2m.sh;
          #cat ${GITHUB_WORKSPACE}/build_far2m.sh;
          if [ ${{ inputs.PLUGINS_EXTRA }} ]; then
            echo "PLUGINS_EXTRA=true" >> $GITHUB_ENV;
          fi

      - name: Checkout far2m
        id: id_check_far2m
        uses: deep-soft/checkout@v3
        with:
          repository: ${{ env.client_payload_repo }}
          path: far2m

      - name: Checkout far2m get ref
        shell: bash
        run: |
         pushd far2m
         far2m_ref=$(/usr/bin/git log -1 --format='%H')
         echo "far2m_ref=$far2m_ref"
